services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: frontend/build
    buildCommand: cd frontend && npm install && npm run build
    branch: main
    pullRequestPreviewsEnabled: true

  - type: web
    name: backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    branch: main
    pullRequestPreviewsEnabled: true
    plan: free

